#!/bin/bash
DICT_IDS=(
	"4"
	"11640"
	"15117"
	"20656"
)
DICT_NAMES=(
	"搜狗标准词库"
	"计算机词汇大全【官方推荐】"
	"日剧、动漫大全【官方推荐】"
  "网络流行新词【官方推荐】"
)
DICT_SHORTS=(
	"sogou_standard"
	"sogou_computer"
	"sogou_anime"
  "sogou_net"
)
DICT_PREFIX="zcheng"
DICT_MASTER_NAME="awesome"
cp ./out/rime/*.yaml ~/Library/Rime
#COPY="$HOME/.config/ibus/rime"
#HOOK_AFTER="rime_deployer --build $COPY /usr/share/rime-data"
